apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patient-db-pvc
  namespace: hms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doctor-db-pvc
  namespace: hms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appointment-db-pvc
  namespace: hms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prescription-db-pvc
  namespace: hms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: billing-db-pvc
  namespace: hms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi